felixse/FluentTerminal

- FluentTerminal.App/Package.appxmanifest
This should remove Splashscreen on Windows 10 16299+. 👍
> Remove splashscreen

- FluentTerminal.App/FluentTerminal.App.csproj
- FluentTerminal.SystemTray/FluentTerminal.SystemTray.csproj
- FluentTerminal.SystemTray/Program.cs
- FluentTerminal.SystemTray/Services/NotificationService.cs
- FluentTerminal.SystemTray/Services/UpdateService.cs
> Add notification for new version

- FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs
- FluentTerminal.App.ViewModels/MainViewModel.cs
- FluentTerminal.Models/Enums/Command.cs
Adding a handful of commands for switching to a specific tab number. This feature in Cmder was addicting, and I found myself constantly trying to use it in FT out of muscle memory.
> Added support for Ctrl+<N> to switch to tab N.

- FluentTerminal.App.Services.Test/KeyboardCommandServiceTests.cs
added missing test for KeyboardCommandService for Command.ToggleWindow
> added missing test for KeyboardCommandService

- README.md
> Prerequisite added

- Install.ps1
> fixed open here dir param.

- FluentTerminal.App.Services/Terminal.cs
- FluentTerminal.App.ViewModels/MainViewModel.cs
- FluentTerminal.App/Adapters/ApplicationViewAdapter.cs
- FluentTerminal.App/App.xaml.cs
> Fix close being called twice

- README.md
> Fix missing Developer mode requirement for Chocolatey install

- FluentTerminal.SystemTray/Services/ConPty/ConPtySession.cs
- FluentTerminal.SystemTray/Services/ConPty/Processes/ProcessFactory.cs
- FluentTerminal.SystemTray/Services/ConPty/Terminal.cs
- FluentTerminal.SystemTray/Services/TerminalsManager.cs
- FluentTerminal.SystemTray/Services/WinPty/WinPtySession.cs
> [WIP] Set TERM_PROGRAM

- FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs
- FluentTerminal.App.ViewModels/MainViewModel.cs
- FluentTerminal.App.ViewModels/Settings/GeneralPageViewModel.cs
- FluentTerminal.App.ViewModels/TerminalViewModel.cs
- FluentTerminal.App/Adapters/ApplicationViewAdapter.cs
- FluentTerminal.App/Views/MainPage.xaml
- FluentTerminal.App/Views/SettingsPages/GeneralSettings.xaml
- FluentTerminal.Models/ApplicationSettings.cs
Fixes #229 and makes @skipmeister123  happy
> Add option to always show original shell title in window title

- FluentTerminal.App.Services/Terminal.cs
- FluentTerminal.App/Views/XtermTerminalView.xaml.cs
> Handle launch fail

- Explorer Context Menu Integration/Install.bat
- Install.ps1
> Fix Context Menu Integration

- FluentTerminal.App.ViewModels/ShellProfileViewModel.cs
Addresses #256
Only change when updated from a checked radio button
> Fix shell profile radio button line-ending binding

- FluentTerminal.App/Views/NativeFrontend/TerminalControl.xaml
- FluentTerminal.App/Views/NativeFrontend/TerminalControl.xaml.cs
- FluentTerminal.App/Views/TerminalView.xaml.cs
- FluentTerminal.Models/TerminalOptions.cs
This is my current work as of now. My current task is trying to get the scroll bar functional.
> Native Renderer Collabate PR

- Icons/FluentTerminal Dark.svg
- Icons/FluentTerminal.svg
I use convertio to generate PNGs - you might prefer another tool or different icon sizes though.
> Add dark and light mode SVG icons for #203

- FluentTerminal.SystemTray/Services/WinPty/WinPtySession.cs
\n doesn't represent as a new line in a verbatim string.
>  fix: new line bug in verbatim string

- FluentTerminal.App/Strings/de/Resources.resw
- FluentTerminal.App/Strings/en/Resources.resw
- FluentTerminal.App/Strings/zh-CN/Resources.resw
Fixes #366 
translation key was causing an issue by targeting a non existing property
> Update translation files

- FluentTerminal.App.ViewModels/ShellProfileViewModel.cs
- FluentTerminal.App/Strings/de/Resources.resw
- FluentTerminal.App/Strings/en/Resources.resw
- FluentTerminal.App/Strings/zh-CN/Resources.resw
> Add missing text for 'delete profile'

- FluentTerminal.App/Views/XtermTerminalView.xaml.cs
> Avoid empty string copying to clipboard on mouse selection.

- FluentTerminal.App/Dialogs/SshInfoDialog.xaml.cs
- FluentTerminal.App/Services/SshHelperService.cs
- FluentTerminal.Models/ShellProfile.cs
- FluentTerminal.Models/SshProfile.cs
- FluentTerminal.Models/StringExtensions.cs
A small PR which fixes a bug related to `mosh://` links and shortcuts.
> Fixing a bug with mosh links.

- FluentTerminal.App/Dialogs/SshInfoDialog.xaml
- FluentTerminal.App/Dialogs/SshProfileSelectionDialog.xaml.cs
Trivial change which solves https://github.com/jumptrading/FluentTerminal/issues/67
> Adding a scrollbar to SSH Info dialog.

- FluentTerminal.App.ViewModels/Settings/SshProfilesPageViewModel.cs
- FluentTerminal.App/Views/SettingsPages/SshProfileSettings.xaml
Unlike local profiles, it doesn't really make sense to have a default SSH profile. The UI elements and backing infrastructure for this has been removed.
> Remove the concept of a default SSH profile

- FluentTerminal.App.ViewModels/TerminalViewModel.cs
The issue is described at https://github.com/jumptrading/FluentTerminal/issues/138.
> Fixing a bug with [ssh] prefix added to WSL

- FluentTerminal.App.ViewModels/Profiles/SshConnectViewModel.cs
- FluentTerminal.App/App.xaml.cs
@felixse , can you please merge this one - it fixes a bug with opening shortcuts in your master.
> Fixing a bug with opening shortcuts.

- FluentTerminal.App.ViewModels/Profiles/SshConnectViewModel.cs
- FluentTerminal.App/Dialogs/SshInfoDialog.xaml
- FluentTerminal.App/Strings/en/Resources.resw
- FluentTerminal.App/Views/SettingsPages/SshProfileSettings.xaml
Adding some translations, fixing remote profiles layout, and fixing a minor bug with quick commands.
> Translations and minor fixes

- FluentTerminal.App.ViewModels/Profiles/SshConnectViewModel.cs
- FluentTerminal.App/Strings/en/Resources.resw
Resolves https://github.com/jumptrading/FluentTerminal/issues/147.
> Implementing more descriptive error messages on invalid quick-command

- FluentTerminal.App/Views/SettingsPages/ShellProfileSettings.xaml
- FluentTerminal.App/Views/SettingsPages/SshProfileSettings.xaml
> Fix crash on profiles

- FluentTerminal.SystemTray/Utilities.cs
Related to https://github.com/jumptrading/FluentTerminal/issues/102
Fast muting of spawned conhost process to play beep sound allows to avoid additional cmd.exe process which hangs in background and whole muting process should be now silent for user.
> Mute spawned conhost audio session to avoid bell sound playing.

- FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs
- FluentTerminal.App.ViewModels/ISessionSuccessTracker.cs
- FluentTerminal.App.ViewModels/Profiles/CommonProfileProviderViewModel.cs
- FluentTerminal.App.ViewModels/Profiles/ProfileProviderViewModelBase.cs
- FluentTerminal.App.ViewModels/Profiles/SshConnectViewModel.cs
- FluentTerminal.App.ViewModels/Settings/GeneralPageViewModel.cs
- FluentTerminal.App.ViewModels/TerminalViewModel.cs
- FluentTerminal.App/Dialogs/CustomCommandDialog.xaml.cs
- FluentTerminal.App/FluentTerminal.App.csproj
- FluentTerminal.App/ViewModels/CommandProfileProviderViewModel.cs
- FluentTerminal.App/ViewModels/DelayedHistorySaver.cs
- FluentTerminal.App/Views/SettingsPages/GeneralSettings.xaml
- FluentTerminal.App/Views/XtermTerminalView.xaml.cs
- FluentTerminal.Models/ApplicationSettings.cs
- FluentTerminal.Models/FluentTerminal.Models.csproj
- FluentTerminal.Models/ShellProfile.cs
This PR solves https://github.com/jumptrading/FluentTerminal/issues/171
> Saving command history only on actually successful session

- FluentTerminal.App/Dialogs/CustomCommandDialog.xaml.cs
- FluentTerminal.App/ViewModels/CommandProfileProviderViewModel.cs
Solves https://github.com/jumptrading/FluentTerminal/issues/177.
> Ignore [Delete] key over profile name in auto-suggest box.

- FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs
- FluentTerminal.App.ViewModels/MainViewModel.cs
- FluentTerminal.App.ViewModels/TerminalViewModel.cs
- FluentTerminal.App/Strings/en/Resources.resw
- FluentTerminal.App/Views/TabBar.xaml
- FluentTerminal.Models/Enums/Command.cs
Related to https://github.com/jumptrading/FluentTerminal/issues/155
Selected tab duplication with CTRL+SHIFT+D or `Duplicate` menu selection on right mouse click at tab's header.
> Duplicate session command.

- FluentTerminal.App/App.xaml
- FluentTerminal.App/Converters/TextMiddleEllipsisConverter.cs
- FluentTerminal.App/FluentTerminal.App.csproj
- FluentTerminal.App/Views/TabBar.xaml
Related to https://github.com/jumptrading/FluentTerminal/issues/188
> Middle ellipsised tab titles.

- FluentTerminal.App/Strings/fr/Resources.resw
all translate in french, I do not know which modifier to change to take into account if it is not automatic
> Multi-language support: Add fr-FR

- FluentTerminal.App/FluentTerminal.App.csproj
- FluentTerminal.App/Services/ApplicationLanguageService.cs
- UpdateTranslations.ps1
> Add French localization

- README.md
English, German, Spanish, French, Simplified Chinese added in languages available
> adding available languages

- README.md
version after the buils status, sonarcloud and gitter,
new top in the center for the logo and the name
it's just beautiful ^^
> Add version + new top

- README.md
Add contributors button (Shields.io button)
> Add contributors button

- FluentTerminal.App.Services/IShellProfileMigrationService.cs
- FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs
- FluentTerminal.App.Services/Implementation/SettingsService.cs
- FluentTerminal.App.Services/Implementation/ShellProfileMigrationService.cs
- FluentTerminal.App.ViewModels/EnvironmentVariableViewModel.cs
- FluentTerminal.App.ViewModels/ShellProfileViewModel.cs
- FluentTerminal.App.ViewModels/ShellProfileViewModelBase.cs
- FluentTerminal.App.ViewModels/SshProfileViewModel.cs
- FluentTerminal.App/App.xaml.cs
- FluentTerminal.App/FluentTerminal.App.csproj
- FluentTerminal.App/Strings/de/Resources.resw
- FluentTerminal.App/Strings/en/Resources.resw
- FluentTerminal.App/Strings/es/Resources.resw
- FluentTerminal.App/Strings/fr/Resources.resw
- FluentTerminal.App/Strings/zh-CN/Resources.resw
- FluentTerminal.App/Views/EnvironmentVariablesView.xaml
- FluentTerminal.App/Views/EnvironmentVariablesView.xaml.cs
- FluentTerminal.App/Views/KeyBindingsView.xaml
- FluentTerminal.App/Views/SettingsPages/ShellProfileSettings.xaml
- FluentTerminal.App/Views/SettingsPages/SshProfileSettings.xaml
- FluentTerminal.Models/ShellProfile.cs
- FluentTerminal.SystemTray/Program.cs
- FluentTerminal.SystemTray/Services/TerminalsManager.cs
> Add option to edit environment variables for profiles

- README.md
> New button

- FluentTerminal.App/Views/SettingsPages/ShellProfileSettings.xaml
- FluentTerminal.App/Views/SettingsPages/SshProfileSettings.xaml
- FluentTerminal.App/Views/SettingsPages/ThemeSettings.xaml
This is a fix for [#443](https://github.com/felixse/FluentTerminal/issues/443).
> Fixed overlap in Settings page.

- FluentTerminal.App.Services.Test/SettingsServiceTests.cs
- FluentTerminal.App.Services/FluentTerminal.App.Services.csproj
- FluentTerminal.App.Services/ISettingsService.cs
- FluentTerminal.App.Services/Implementation/SettingsService.cs
- FluentTerminal.App.ViewModels/FluentTerminal.App.ViewModels.csproj
- FluentTerminal.App.ViewModels/MainViewModel.cs
- FluentTerminal.App.ViewModels/Profiles/ProfileProviderViewModelBase.cs
- FluentTerminal.App.ViewModels/TerminalViewModel.cs
- FluentTerminal.App/App.xaml.cs
- FluentTerminal.App/Views/TerminalView.xaml.cs
- FluentTerminal.Models/Messages/ApplicationSettingsChangedMessage.cs
- FluentTerminal.Models/Messages/CurrentThemeChangedMessage.cs
- FluentTerminal.Models/Messages/KeyBindingsChangedMessage.cs
- FluentTerminal.Models/Messages/ShellProfileAddedMessage.cs
- FluentTerminal.Models/Messages/ShellProfileDeletedMessage.cs
- FluentTerminal.Models/Messages/SshProfileAddedMessage.cs
- FluentTerminal.Models/Messages/SshProfileDeletedMessage.cs
- FluentTerminal.Models/Messages/ThemeAddedMessage.cs
- FluentTerminal.Models/Messages/ThemeDeletedMessage.cs
- FluentTerminal.SystemTray/Services/TerminalsManager.cs
This PR solves https://github.com/jumptrading/FluentTerminal/issues/143
Also it may solve some other detected leaks like https://github.com/jumptrading/FluentTerminal/issues/190
> Replaces events with MVVMLight Messenger

- FluentTerminal.App.Services.Test/SettingsServiceTests.cs
- FluentTerminal.App.Services/ISettingsService.cs
- FluentTerminal.App.Services/Implementation/SettingsService.cs
- FluentTerminal.App.ViewModels/MainViewModel.cs
- FluentTerminal.App.ViewModels/Settings/ThemesPageViewModel.cs
- FluentTerminal.App.ViewModels/TerminalViewModel.cs
- FluentTerminal.App/Views/TerminalView.xaml.cs
- FluentTerminal.Models/Messages/TerminalOptionsChangedMessage.cs
Killing the last survivor from https://github.com/felixse/FluentTerminal/pull/519 :)
(Not sure how I've forgot it survived in the first place.)
> Replaces events with MVVMLight Messenger 2

- FluentTerminal.App.ViewModels/ITerminalView.cs
- FluentTerminal.App.ViewModels/TerminalViewModel.cs
- FluentTerminal.App/Views/XtermTerminalView.xaml.cs
It solves https://github.com/jumptrading/FluentTerminal/issues/201
@felixse , although this pasting produces much nicer results, it may require some additional testing with different clipboard contents. I've tested **a lot** with different content, and so far it works like charm.
I suggest merging, and if it shows some issues in production, we can easy revert back...
> Implement xterm paste instead of writing to input stream

- FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs
- FluentTerminal.App.ViewModels/Settings/TerminalPageViewModel.cs
- FluentTerminal.App/Views/SettingsPages/TerminalSettings.xaml
- FluentTerminal.Client/src/index.ts
- FluentTerminal.Models/TerminalOptions.cs
#527 
Replaced `BoldText` toggle with `FontWeight` slider.
> Add font weight setting

- FluentTerminal.App/FluentTerminal.App.csproj
- FluentTerminal.App/Services/ApplicationLanguageService.cs
- FluentTerminal.App/Strings/he/Resources.resw
- README.md
- UpdateTranslations.ps1
I've translate most of the strings on POEditor and imported the Resource.resw file into the project. 
However, the app might need some UI work for RTL languages such as Hebrew or Arabic.
> Added hebrew translation

- FluentTerminal.App/Dialogs/CustomCommandDialog.xaml
- FluentTerminal.App/ViewModels/CommandItemViewModel.cs
Solves https://github.com/jumptrading/FluentTerminal/issues/185
> Select command with mosue in "Quick Launch" dialog

- FluentTerminal.App/Dialogs/CustomCommandDialog.xaml
- FluentTerminal.App/Dialogs/CustomCommandDialog.xaml.cs
Solves https://github.com/jumptrading/FluentTerminal/issues/236
I've had to implement a hack to enforce Tab-selection.
> Tab-selection in "Quick Launch" dialog

- FluentTerminal.App.Services/ICommandHistoryService.cs
- FluentTerminal.App.Services/Implementation/CommandHistoryService.cs
- FluentTerminal.App.Services/Implementation/MoshBackwardCompatibility.cs
- FluentTerminal.App.ViewModels/DelayedHistorySaver.cs
- FluentTerminal.App.ViewModels/MainViewModel.cs
- FluentTerminal.App.ViewModels/ProfileCommandViewModel.cs
- FluentTerminal.App/Dialogs/CustomCommandDialog.xaml.cs
- FluentTerminal.App/FluentTerminal.App.csproj
- FluentTerminal.App/Services/CommandHistoryService.cs
- FluentTerminal.App/Strings/en/Resources.resw
- FluentTerminal.App/ViewModels/CommandProfileProviderViewModel.cs
- FluentTerminal.App/Views/MainPage.xaml
- FluentTerminal.App/Views/MenuExtension.cs
- FluentTerminal.Models/ExecutedCommand.cs
- FluentTerminal.Models/Messages/CommandHistoryChangedMessage.cs
Solves https://github.com/jumptrading/FluentTerminal/issues/235
> "Recent" menu implemented

- README.md
If that's wrong in any other file I would ask to fix there too
> It's "brazilian", not "brasilian"

- FluentTerminal.App/Strings/pt-BR/Resources.resw
Why "texto em negrito" and not "texto negrito"? https://support.office.com/pt-br/article/Colocar-o-texto-em-negrito-7D24F3E1-74C1-47F2-88B0-2601779F7CB2
Why "papel de parede" and not "plano de fundo"? https://trends.google.com.br/trends/explore?q=papel%20de%20parede,plano%20de%20fundo
> Fixing some gramatical errors and unusual words

- FluentTerminal.App.Services/IApplicationView.cs
- FluentTerminal.App.ViewModels/FluentTerminal.App.ViewModels.csproj
- FluentTerminal.App.ViewModels/MainViewModel.cs
- FluentTerminal.App.ViewModels/Profiles/ProfileProviderViewModelBase.cs
- FluentTerminal.App.ViewModels/Profiles/SshConnectViewModel.cs
- FluentTerminal.App.ViewModels/Settings/AboutPageViewModel.cs
- FluentTerminal.App.ViewModels/TerminalViewModel.cs
- FluentTerminal.App/Adapters/ApplicationViewAdapter.cs
- FluentTerminal.App/App.xaml.cs
- FluentTerminal.App/FluentTerminal.App.csproj
- FluentTerminal.App/Utilities/DispatcherExtensions.cs
- FluentTerminal.App/ViewModels/CommandProfileProviderViewModel.cs
- FluentTerminal.App/Views/XtermTerminalView.xaml.cs
Part of https://github.com/jumptrading/FluentTerminal/issues/237
The key changes are:
- Now we can specify priority of the action that will be scheduled to dispatcher (i.e. `CoreDispatcherPriority.Low`);
- `enforceNewSchedule` now defaults to `false` (I've reviewed all the usages and concluded that it's safe);
- Now supports scheduling functions which are returning a value.
> Dispatcher usage improvements

- FluentTerminal.App/Views/XtermTerminalView.xaml.cs
Felix, I've just noticed that I've screwed up resizing in one of my previous PRs. Here's the fix. Please merge it asap. Sorry and thanks!
> Fixing resizing bug - pls do it asap

- FluentTerminal.App.ViewModels/MainViewModel.cs
Fixes https://github.com/jumptrading/FluentTerminal/issues/247
> Select terminal after closing issue fixed

- FluentTerminal.RuntimeComponent/WebAllowedObjects/TerminalBridge.cs
Related to https://github.com/jumptrading/FluentTerminal/issues/237
Will post another comment (see below) which describes what was wrong here.
> Improving TerminalBridge

- FluentTerminal.SystemTray/Program.cs
- FluentTerminal.SystemTray/Services/AppCommunicationService.cs
- FluentTerminal.SystemTray/Services/ConPty/ConPtySession.cs
Related to https://github.com/jumptrading/FluentTerminal/issues/237.
Very few changes here. It will look that I've changed `Program.cs` in `SystemTray` project significantly, but it's only because I've wrapped significant part of `main` method to `using` statement (which changed indentation, so git reports many changed lines). In reality there are only few changes.
> Removing Task.Run or replacing it with Task.Factory.StartNew

- FluentTerminal.App.Services/IApplicationView.cs
- FluentTerminal.App.Services/Implementation/TrayProcessCommunicationService.cs
- FluentTerminal.App.ViewModels/MainViewModel.cs
- FluentTerminal.App/Adapters/AppServiceConnectionAdapter.cs
- FluentTerminal.App/Adapters/ApplicationViewAdapter.cs
- FluentTerminal.App/Adapters/MessageDialogAdapter.cs
- FluentTerminal.App/App.xaml.cs
- FluentTerminal.App/Views/MainPage.xaml.cs
Related to https://github.com/jumptrading/FluentTerminal/issues/237
Changes are rather trivial:
- Removing `async`/`await` where it isn't needed (as explained in one of my previous PRs);
- Renaming async methods by appending "Async" suffix (i.e. `DoSomething` to `DoSomethingAsync`).
- Also some minor changes/improvements if I spotted something...
> Reviewed async pattern in App.xaml.cs

- FluentTerminal.App/Adapters/AppServiceConnectionAdapter.cs
Something strange happened after merging things. It's fixed now.
> BUG master doesn't compile

- README.md
Indian to Hindi.
Indian is not a language
Fixes #630
> Changed README languages supported

- FluentTerminal.App.Services/Utilities/I18N.cs
- FluentTerminal.App/ViewModels/CommandProfileProviderViewModel.cs
**Merge https://github.com/felixse/FluentTerminal/pull/641 first!**
Solves https://github.com/jumptrading/FluentTerminal/issues/260
> Command validation bug fixed

- FluentTerminal.App.ViewModels/TerminalViewModel.cs
- FluentTerminal.App/Views/XtermTerminalView.xaml.cs
Fixes https://github.com/jumptrading/FluentTerminal/issues/264
> Fixes a bug with Copy crashing the app

- FluentTerminal.SystemTray/Services/AppCommunicationService.cs
Fixes https://github.com/jumptrading/FluentTerminal/issues/266
> Removes domain name from user name.

- FluentTerminal.App/Dialogs/CustomCommandDialog.xaml.cs
- FluentTerminal.App/Services/CommandHistoryService.cs
Solves https://github.com/jumptrading/FluentTerminal/issues/263
> Fixed a bug with profile change in history commands not being preserved

- FluentTerminal.App/Views/TabBar.xaml
- FluentTerminal.App/Views/TabBar.xaml.cs
Improved version of https://github.com/felixse/FluentTerminal/pull/618
Tested and works.
> Improved TabBar.

- FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs
- FluentTerminal.App.ViewModels/Profiles/ProfileProviderViewModelBase.cs
- FluentTerminal.App/App.xaml.cs
- FluentTerminal.App/CommandLineArguments/RunVerb.cs
- FluentTerminal.App/Dialogs/CustomCommandDialog.xaml
- FluentTerminal.App/Dialogs/SshInfoDialog.xaml
- FluentTerminal.App/Strings/en/Resources.resw
- FluentTerminal.App/Views/SettingsPages/ShellProfileSettings.xaml
- FluentTerminal.App/Views/SettingsPages/SshProfileSettings.xaml
- FluentTerminal.Models/ShellProfile.cs
- FluentTerminal.SystemTray/BufferedReader.cs
- FluentTerminal.SystemTray/Services/ConPty/ConPtySession.cs
- FluentTerminal.SystemTray/Services/WinPty/WinPtySession.cs
Solves https://github.com/felixse/FluentTerminal/issues/669
> "Use buffer" profile settings implemented

- FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs
- FluentTerminal.App.Services/Terminal.cs
- FluentTerminal.App.ViewModels/ITerminalView.cs
- FluentTerminal.App.ViewModels/MainViewModel.cs
- FluentTerminal.App.ViewModels/TerminalViewModel.cs
- FluentTerminal.App/Strings/ar-iq/Resources.resw
- FluentTerminal.App/Strings/ar/Resources.resw
- FluentTerminal.App/Strings/az/Resources.resw
- FluentTerminal.App/Strings/de/Resources.resw
- FluentTerminal.App/Strings/en/Resources.resw
- FluentTerminal.App/Strings/es/Resources.resw
- FluentTerminal.App/Strings/fr/Resources.resw
- FluentTerminal.App/Strings/he/Resources.resw
- FluentTerminal.App/Strings/hi/Resources.resw
- FluentTerminal.App/Strings/id/Resources.resw
- FluentTerminal.App/Strings/it/Resources.resw
- FluentTerminal.App/Strings/ja/Resources.resw
- FluentTerminal.App/Strings/ko/Resources.resw
- FluentTerminal.App/Strings/nl/Resources.resw
- FluentTerminal.App/Strings/pl/Resources.resw
- FluentTerminal.App/Strings/pt-BR/Resources.resw
- FluentTerminal.App/Strings/ro/Resources.resw
- FluentTerminal.App/Strings/ru/Resources.resw
- FluentTerminal.App/Strings/uk/Resources.resw
- FluentTerminal.App/Strings/zh-Hans/Resources.resw
- FluentTerminal.App/Strings/zh-Hant/Resources.resw
- FluentTerminal.App/Views/TerminalView.xaml
- FluentTerminal.App/Views/XtermTerminalView.xaml.cs
- FluentTerminal.Models/Enums/Command.cs
Fixes https://github.com/jumptrading/FluentTerminal/issues/222
Overlay to reconnect/close tab; Shortcut to reconnect tab.
> Reconnect failed tab.

- FluentTerminal.SystemTray/Services/ConPty/ConPtySession.cs
- FluentTerminal.SystemTray/Services/ConPty/PseudoConsole.cs
- FluentTerminal.SystemTray/Services/ConPty/Terminal.cs
> Fixes random hanging on closing of ConPty session by disposing pseudoconsole before its writing pipe.

- FluentTerminal.App/Views/XtermTerminalView.xaml.cs
- FluentTerminal.Client/src/index.ts
- FluentTerminal.RuntimeComponent/Interfaces/IxtermEventListener.cs
- FluentTerminal.RuntimeComponent/WebAllowedObjects/TerminalBridge.cs
On restart of OpenSSH session prints message "Reconnecting current session..." and removes CSIs to clear the screen, set cursor position. As result: cursor position is not reset and the flow looks natural for users.
> Enhance OpenSSH output on restart of session.

- FluentTerminal.SystemTray/SystemTrayApplicationContext.cs
Disposes of the tray icon so that it is cleared from tray once the application is closed
> fixes #790

- FluentTerminal.App.ViewModels/TerminalViewModel.cs
Also copies title to other tabs
> fixes #761

- FluentTerminal.App/Strings/nl/Resources.resw
Add new translations.
Fix typo's.
> Update Dutch translations

- README.md
Created a vscode extension to open folders on visual studio code on fluent terminal. Currently it opens it in defined profile in Fluent Terminals settings.
> ✨ Updated Readme to include link to vscode extension

- FluentTerminal.App/Strings/tr/Resources.resw
Turkish translation has been updated with clean Turkish.
> Clear Turkish Support
