felixse/FluentTerminal

FluentTerminal.Models/Enums/ExtendedVirtualKey.cs, FluentTerminal.SystemTray/Utilities.cs
Support backtick character `` ` ``   for keybinding
=> Add support grave accent for keybinding

README.md
Updated the readme to provide instructions about enabling sideloading apps, and changing the wording around developer mode to be optional for _users_, at this point. Added the extra step to manually enable the loopback exemption if you've only got sideloading apps enabled.
=> Update readme to address issues with loopback exemption

FluentTerminal.App/Views/SettingsPages/GeneralSettings.xaml, FluentTerminal.App/Views/SettingsPages/MouseSettings.xaml, FluentTerminal.App/Views/SettingsPages/ShellProfileSettings.xaml, FluentTerminal.App/Views/SettingsPages/ThemeSettings.xaml, FluentTerminal.Client/package-lock.json
This fixes the scrolling issue mentioned in #63
=> Fixed Issue #63

FluentTerminal.App/Services/ClipboardService.cs
Returning null Task reference was causing a crash when attempting to paste a non-text buffer.
=> Return an empty string when attempting to paste non-text clipboard buffer

FluentTerminal.App/Views/SettingsPage.xaml
Disable compact mode for the settings window (which removes the sidebar) entirely. Instead now the side bar is just collapsed at `560` (I guess pixels?).
=> Fix display issue when settings window is too narrow

FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs, FluentTerminal.App.ViewModels/Settings/GeneralPageViewModel.cs, FluentTerminal.App/Views/SettingsPages/GeneralSettings.xaml, FluentTerminal.Models/ApplicationSettings.cs, FluentTerminal.SystemTray/Program.cs
As requested in #137, added an option to the settings to enable or disable the tray icon. The current implementation requires the user to restart FluentTerminal in order for the option to take affect (and they're informed about this in the UI)
Ideally the system tray icon should just appear/disappear as the option is toggled, but I couldn't get that to work. The [`SettingsService` in Program.cs](https://github.com/felixse/FluentTerminal/blob/d9b7052e871ed28e0e48d10f85f73371b3e58787/FluentTerminal.SystemTray/Program.cs#L49) does not respond to the [`ApplicationSettingsChanged` event](https://github.com/felixse/FluentTerminal/blob/master/FluentTerminal.App.Services/Implementation/SettingsService.cs#L49) because the Settings views use the [`SettingsService` in …
=> Add "Show in system tray" option

FluentTerminal.Client/src/index.html, FluentTerminal.Client/src/index.js, FluentTerminal.Client/src/style.css
Hello,
first of all - amazing app, what I've been longing to find or wanting to make myself for a long time.
Since Surface Pro is my mainly driver, the precision touhpad scrolling issue #114 has been a dealbreaker for a while now so I decided to fix it. I've been making some EdgeHTML & HTML UWP apps for a while so I already came across this is pretty basic bug (*unless MS decided to market it a feature and call it a day :D*) plaguing all my projects.
**What's been happening?**
Scroll events are getting captured by `<body>` or `<html>` and since it has no scrollbar and no content larger than elements visible portion, EdgeHTML does the overflow bounce effect.
There's also adjacent issue to the scrolling which only surfaces on precision touchpads - pinch zooming. Also side scrolling. …
=> fix #114 scrolling issue on presicion touchpads

FluentTerminal.App/Dialogs/InputDialog.xaml, FluentTerminal.App/Dialogs/InputDialog.xaml.cs
... As if the primary button is pressed.
Closes #174 (the original request)
I did not figure out how to have `result` be equal to `ContentDialogResult.Primary` (as seen [here](https://github.com/felixse/FluentTerminal/blob/6be29f49d7c5db18c4fa4c49261f56cb6dfa805a/FluentTerminal.App/Dialogs/InputDialog.xaml.cs#L20)) so I used an internal variable to communicate the intent of closing the dialog.
=> Press enter to close an InputDialog

FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs, FluentTerminal.App.ViewModels/Settings/TerminalPageViewModel.cs, FluentTerminal.App/Views/SettingsPages/TerminalSettings.xaml, FluentTerminal.Client/src/index.js, FluentTerminal.Models/TerminalOptions.cs
Closes #182
Adds a toggle to the Terminal Page to enable/disable bold text in terminals. Currently, from my testing, when `BoldText` is enabled there is no real distinction between normal and bold text in most fonts, I also addressed this in [this comment](https://github.com/felixse/FluentTerminal/issues/182#issuecomment-455901102).
Currently the conversion from boolean to `fontWeight` and `fontWeightBold` value is performed 2x each, alternatively we could use transformer functions, e.g. ⬇️, but this seems like overkill to me.
```javascript
term.setOption('fontWeight', boldToFontWeight(options.boldText));
term.setOption('fontWeightBold', boldToFontWeightBold(options.boldText));
...
function boldToFontWeight(boldText) {
return options.boldText ? 'bold' : 'normal';
}
function …
```
=> Add option to use bold text in terminals

FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs, FluentTerminal.App.ViewModels/MainViewModel.cs, FluentTerminal.App.ViewModels/TerminalViewModel.cs, FluentTerminal.Models/Enums/Command.cs, FluentTerminal.Models/KeyBindings.cs
As per [the suggestion](https://github.com/felixse/FluentTerminal/issues/174#issuecomment-454673472) by @ChristianSauer. I set the default binding to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd>.
=> Add keybinding to change the (current) tab title

Install.ps1
Allows scripted install of context menu integration with `-ForceContextMenu` switch
=> installation switch to force context menu integration automatically

FluentTerminal.App.Services/EventArgs/NewWindowRequestedEventArgs.cs, FluentTerminal.App.Services/EventArgs/ProfileSelectEventArgs.cs, FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs, FluentTerminal.App.ViewModels/MainViewModel.cs, FluentTerminal.App/App.xaml.cs, FluentTerminal.Models/Enums/Command.cs, FluentTerminal.Models/KeyBindings.cs
As per #96 and [this comment](https://github.com/felixse/FluentTerminal/pull/193#issuecomment-460706953) I added a keybinding to open a new configurable window. The default binding is <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd>.
1] It may be possible to rely less on a parameter (`showProfileSelection`) in _App.xaml.cs_, but I personally don't think that's a good idea.
* * *
2] There are now two `EventArgs` (namely `CancelableEventArgs` and `ProfileSelectEventArgs`) that basically only hold a boolean value (`cancelled` and `ShowProfileSelection` respectively). On the one hand one the naming helps the reader understand the code, on the other hand it you have (albeit simple) duplicate code. I can refactor the `EventArgs` into a single `BooleanEventArgs` class like so:
```c#
// Current use …
```
=> Add keybinding for configurable new window

FluentTerminal.SystemTray/Services/TerminalsManager.cs
This PR changes `TERM` from `xterm` to `xterm-256color` to be better consistent with other xterm.js-based Terminals
- **Hyper:** https://github.com/zeit/hyper/blob/571231e4438cae4eec3e88fa4aab398b5b269433/app/session.js#L32-L36
- **Terminus:** https://github.com/Eugeny/terminus/blob/9e81f0aa0e7274fdddc110ea9c77ca42f500896e/terminus-terminal/src/services/sessions.service.ts#L96-L101
=> set `TERM` to `xterm-256color`

FluentTerminal.Client/src/index.js
Add-ons imported as per Xterm documentation recommendations: https://xtermjs.org/docs/guides/using-addons/
Importing from dist in JS is implementation dependent - it is better to use the `export`ed paths, as this is the externally exposed API from the module.
=> Use idiomatic JS import style in web client

FluentTerminal.App.ViewModels/ShellProfileViewModel.cs, FluentTerminal.App/Views/SettingsPages/ShellProfileSettings.xaml, FluentTerminal.Models/Enums/LineEndingStyle.cs, FluentTerminal.Models/ShellProfile.cs
I've been unable to use multi-line paste in interactive terminal programs (e.g. nano editor) as it expects to see the [Enter] key as [CR].
Sending pasted line-endings as [CR] also still works for all my non-interactive situations, as the default WSL Ubuntu 16/18 `stty icrnl` configuration will convert [CR] to [LF].
=> Add convert line endings to CR option

Install.ps1
I saw in the install PowerShell script, at line 331, there is a comparison with a right hand null element. This will produce a warning, because PowerShell might not do the comparisons correctly if the $null element is not on the left side. You can read why from the link below (see below). This PR is to remove the warning 
https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/PossibleIncorrectComparisonWithNull.md
=> move the $null to the left side of the operator

FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs
The build-in Ubuntu profile has the yellows and cyans swapped. This fixes that.
=> Un-swap Ubuntu yellow and cyan

FluentTerminal.SystemTray/Services/ConPty/ConPtySession.cs, FluentTerminal.SystemTray/Services/WinPty/WinPtySession.cs
Fixes console output rendering [issues ](https://github.com/jumptrading/FluentTerminal/issues/13) that appear on whole buffer frame update (happens on usage of tmux, mosh).
More details:
- Similar issues happen both for ConPTY and WinPTY on running `tmux`
- Issue disappears if to increase output std reading buffer. But if to resize the terminal to exceed the buffer the issue come back again. 
- "Unexpected" characters appear between calls of `_appServiceConnection.SendMessageAsync(CreateMessage(e));`
Changes in PR read output console stream for whole terminal buffer at once to execute `_appServiceConnection.SendMessageAsync` only single time per "frame".
=> Read whole terminal frame at once to avoid console data append glitches

FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs
Many of FluentTerminal's default keybindings collide with commonly used
default keys in various terminal apps. Use defaults that are less likely
to cause problems to provide a better out-of-the-box experience. Many of
the bindings are inspired by gnome-terminal's defaults.
Also, the `false` modifiers in the default keybinding specifications
have been removed. This makes it easier to see which modifiers are
actually in use.
=> Less conflicting default keybindings

FluentTerminal.App.ViewModels/MainViewModel.cs, FluentTerminal.Models/ShellProfile.cs, FluentTerminal.Models/SshProfile.cs
Now FluentTerminal correctly finds `ssh.exe` when run as a 32-bit process on 64-bit operational system.
Also, now to find paths to system directories it uses system calls instead of using hardcoded paths.
=> Fix finding SSH when run as 32-bit process on a 64-bit OS

FluentTerminal.App.Services.Test/TrayProcessCommunicationServiceTests.cs, FluentTerminal.App.Services/ITrayProcessCommunicationService.cs, FluentTerminal.App.Services/Implementation/TrayProcessCommunicationService.cs, FluentTerminal.App.Services/Terminal.cs, FluentTerminal.Models/Requests/TerminalExitedRequest.cs, FluentTerminal.Models/TerminalExitStatus.cs, FluentTerminal.SystemTray/Native/ProcessApi.cs, FluentTerminal.SystemTray/Services/AppCommunicationService.cs, FluentTerminal.SystemTray/Services/ConPty/ConPtySession.cs, FluentTerminal.SystemTray/Services/ConPty/Processes/Process.cs, FluentTerminal.SystemTray/Services/ConPty/Terminal.cs, FluentTerminal.SystemTray/Services/ITerminalSession.cs, FluentTerminal.SystemTray/Services/TerminalsManager.cs, FluentTerminal.SystemTray/Services/WinPty/WinPtySession.cs
Make the shell process's exit code available to the main app so that
actions can be taken depending on whether the shell command was
successful or not.
Later work will build on this so that failed commands will result in
tabs being left open when the shell command fails. This will help when
troubleshooting incorrectly configured profiles, SSH connection issues
etc.
Exit codes are passed up for both WinPty and ConPty based terminals.
=> Bubble up shell process exit codes

FluentTerminal.App.Services/Terminal.cs, FluentTerminal.App.ViewModels/TerminalViewModel.cs, FluentTerminal.App/Views/TabBar.xaml
Do not close tab if shell process closes with an error. An indicator is shown in the tab's title when this happens.
Example:
=> Leave tabs open on error

FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs
As per the subject, I believe changing the line style ending default for WSL should address issue #310.  Unix terminals typically expect a LF ending and windows will default generally to CR+LF.  At least in my testing changing to LF fixes the multi-line copy paste issue, so suggest changing the default for WSL.
=> Updated default line ending for WSL to address issue #310

FluentTerminal.App.ViewModels/SshConnectionInfoViewModel.cs
To avoid extra reconfiguration of opened mosh ports the default mosh ports should be used by FT
=> Standardize default mosh ports to the range of 60001:60999

FluentTerminal.App.Services/ISshConnectionInfo.cs, FluentTerminal.App.Services/ISshHelperService.cs, FluentTerminal.App.ViewModels/SshConnectionInfoViewModel.cs, FluentTerminal.App/App.xaml.cs, FluentTerminal.App/Services/SshHelperService.cs
The key thing that I've needed to do is to ensure that the window is created before we have `ShellProfile`. So far we were creating the window only with `ShellProfile` ready. Now we need "SSH Info" dialog in order to create `ShellProfile`, and we need a window to be created in order to show "SSH Info" dialog...
=> Fixed a bug with clicking links without having the app opened.

FluentTerminal.App/App.xaml.cs
PR to avoid crashes on multiple launch requests.
Crash repro steps:
- Launch powershell command line
- Quickly one by one execute multiple times following command to launch FT:
```
explorer.exe shell:AppsFolder\$(get-appxpackage -name 53621FSApps.FluentTerminal | select -expandproperty PackageFamilyName)!App
```
=> Ignore multiple launch requests at the same time

FluentTerminal.App.Services.Test/FluentTerminal.App.Services.Test.csproj, FluentTerminal.App.Services.Test/TrayProcessCommunicationServiceTests.cs, FluentTerminal.App.Services/Constants.cs, FluentTerminal.App.Services/IAppServiceConnection.cs, FluentTerminal.App.Services/ITrayProcessCommunicationService.cs, FluentTerminal.App.Services/Implementation/TrayProcessCommunicationService.cs, FluentTerminal.App.Services/Terminal.cs, FluentTerminal.App/Adapters/AppServiceConnectionAdapter.cs, FluentTerminal.Models/IMessage.cs, FluentTerminal.Models/MessageKeys.cs, FluentTerminal.Models/Requests/CreateTerminalRequest.cs, FluentTerminal.Models/Requests/DisplayTerminalOutputRequest.cs, FluentTerminal.Models/Requests/GetAvailablePortRequest.cs, FluentTerminal.Models/Requests/GetUserNameRequest.cs, FluentTerminal.Models/Requests/ResizeTerminalRequest.cs, FluentTerminal.Models/Requests/SaveTextFileRequest.cs, FluentTerminal.Models/Requests/SetToggleWindowKeyBindingsRequest.cs, FluentTerminal.Models/Requests/TerminalExitedRequest.cs, FluentTerminal.Models/Responses/CommonResponse.cs, FluentTerminal.Models/Responses/CreateTerminalResponse.cs, FluentTerminal.Models/Responses/GetAvailablePortResponse.cs, FluentTerminal.Models/Responses/GetUserNameResponse.cs, FluentTerminal.Models/TerminalExitStatus.cs, FluentTerminal.Models/TerminalOutput.cs, FluentTerminal.SystemTray/Services/AppCommunicationService.cs, FluentTerminal.SystemTray/Services/ConPty/ConPtySession.cs, FluentTerminal.SystemTray/Services/ITerminalSession.cs, FluentTerminal.SystemTray/Services/TerminalsManager.cs, FluentTerminal.SystemTray/Services/WinPty/WinPtySession.cs
Somewhat similar to #232 
- Minimized message keys
- No more conversions between ValueSet and Dictionary
- Removed additional Request abstraction for sending buffers from/to terminal
- Remaining Requests are still serialized to JSON for now
- Changed datatype of terminal id to byte to squeeze out a few more bytes
=> Improve IPC

FluentTerminal.App/Views/XtermTerminalView.xaml.cs
When FluentTerminal's window is resized many resize events are sent to
the terminal in quick succession. These rapid terminal size changes
while other output is being sent to the terminal can result in
display corruption.
In this change:
- Resize events are "debounced", greatly reducing the number of
resize events being sent to the underlying terminal.
- Output to the terminal is blocked while resize events are processed.
The blocked output is temporarily buffered until the resize event
should have been processed by the underlying terminal.
The net result is that window resizes are *much* less likely to result
in corrupted buffer output. Corruption can still happen however,
especially in cases of very high rates of output being sent to the
terminal.
The mostly solves #373.
=> Debounce terminal resize events

FluentTerminal.App.Services/Adapters/ApplicationDataContainerAdapter.cs, FluentTerminal.App.Services/Implementation/TrayProcessCommunicationService.cs
This fixes a new regression introduced in 0065827bf (SSH profile support) which causes any keybinding change to crash FT. 
It's not clear to me why these JSON serializer settings were introduced so there might be a better way to fix this.
=> Fix crash when any keybinding is changed

FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs, FluentTerminal.App/Strings/en/Resources.resw, FluentTerminal.App/Views/KeyBindingsView.xaml, FluentTerminal.Models/Enums/Command.cs
- Added missing resource strings for new SSH bindings. Without these the settings page has no labels for these bindings.
- Rationalise default SSH keybindings. The logic is:
- Adhoc SSH tabs and windows are based around the Y key
- SSH profile tabs and windows are based around the U key (next to Y and easier to reach than Z)
- Reorder commands so that related keybindings are grouped together on the keybindings settings page
=> Clean up SSH keybindings

FluentTerminal.Client/package.json, FluentTerminal.Client/src/index.ts
Related to the Issue https://github.com/jumptrading/FluentTerminal/issues/106
Fluent updated to use patched xterm 4.14.1 from forked branch https://github.com/MaxRis/xterm.js/tree/3.14.1-patched
https://github.com/MaxRis/xterm.js/commit/0be6a73d3bceb8b3b9a77ba831bf4572ea01a286 introduces `wordSeparator` option as it was suggested there https://github.com/xtermjs/xterm.js/issues/2091
Fluent redefines words separators with additional ":" and ";" symbols to be recognized as separators.
=> Use patched xterm 3.14.1 with wordSeparator option

FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs, FluentTerminal.App.ViewModels/Settings/GeneralPageViewModel.cs, FluentTerminal.App.ViewModels/Settings/SshProfilesPageViewModel.cs, FluentTerminal.App/Services/SshHelperService.cs, FluentTerminal.App/Views/SettingsPages/GeneralSettings.xaml, FluentTerminal.Models/ApplicationSettings.cs
Adds settings option to use Mosh by default for ssh connections.
Requires translations for `UseMoshByDefault.Header` key in resources. Default string value from this PR is `Default to Mosh for SSH connections`.
PR related to https://github.com/jumptrading/FluentTerminal/issues/114
=> Settings option to turn on Mosh by default for ssh connections

FluentTerminal.App.ViewModels/TerminalViewModel.cs
Makes tab titles for ssh and mosh nicer, as required in https://github.com/jumptrading/FluentTerminal/issues/65
@felixse - this one requires another string in resources: `"Authenticate"`.
=> Making tab names for ssh and mosh nicer.

FluentTerminal.App/App.xaml.cs, FluentTerminal.App/CommandLineArguments/SettingsVerb.cs, FluentTerminal.App/Strings/en/Resources.resw
Fixes https://github.com/jumptrading/FluentTerminal/issues/130
@felixse could you please let me know if it's fine that I've added strings "SettingsExported" and "SettingsImported" to EN only resources.
=> Fixes broken settings export/import. Notifies user on completion.

FluentTerminal.Models/SshProfile.cs
Fixes #https://github.com/jumptrading/FluentTerminal/issues/133
ConPTY is selected by default for new SSH profiles and on new configurable SSH connections.
=> Use ConPTY by default for SSH connections

FluentTerminal.Client/package.json
Incorporates fix from xterm.js's upstream https://github.com/xtermjs/xterm.js/pull/2278 .
Fixes #420
=> [Xterm.JS] Reset wrapped line flag.

FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs, FluentTerminal.App.ViewModels/Settings/GeneralPageViewModel.cs, FluentTerminal.App/Services/ClipboardService.cs, FluentTerminal.App/Views/SettingsPages/GeneralSettings.xaml, FluentTerminal.Models/ApplicationSettings.cs
Standard MacOS's Terminal.app and Ubuntu's terminal don't do right trimming of copied lines.
cmd.exe and iTerm2(MacOS) do right trimming.
Difference in copied white-spaces with/without turned on new added settings option:
Related to https://github.com/jumptrading/FluentTerminal/issues/76
=> Settings option to right trim lines on coping to clipboard.

FluentTerminal.App.ViewModels/Settings/ProfilesPageViewModel.cs
We don't need to save the profile unless "Save" button is clicked. Before this change I've had an issue with creating new shell profiles.
=> Fixing a bug with creating new profiles.

FluentTerminal.App.Services/ITrayProcessCommunicationService.cs, FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs, FluentTerminal.App.Services/Implementation/TrayProcessCommunicationService.cs, FluentTerminal.App.ViewModels/Settings/GeneralPageViewModel.cs, FluentTerminal.App.ViewModels/SettingsViewModel.cs, FluentTerminal.App/Strings/en/Resources.resw, FluentTerminal.App/Views/SettingsPages/GeneralSettings.xaml, FluentTerminal.Models/ApplicationSettings.cs, FluentTerminal.Models/Requests/MuteTerminalRequest.cs, FluentTerminal.SystemTray/FluentTerminal.SystemTray.csproj, FluentTerminal.SystemTray/Program.cs, FluentTerminal.SystemTray/Services/AppCommunicationService.cs, FluentTerminal.SystemTray/Utilities.cs, FluentTerminal.SystemTray/VolumeControl.cs
Fixes #386 
- Global settings option is added to mute terminal beeps (mute state is applied to all currently running conhost processes with accessible audio sessions).
- On time of tray process startup global mute setting is applied.
- Default audio device is muted while manually generated beep to trigger conhost audio sessions is playing.
=> Settings option to mute conhost.

FluentTerminal.App.Services/ISettingsService.cs, FluentTerminal.App.Services/ITrayProcessCommunicationService.cs, FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs, FluentTerminal.App.Services/Implementation/SettingsService.cs, FluentTerminal.App.Services/Implementation/TrayProcessCommunicationService.cs, FluentTerminal.App.ViewModels/Settings/GeneralPageViewModel.cs, FluentTerminal.App/App.xaml.cs, FluentTerminal.App/Views/SettingsPages/GeneralSettings.xaml, FluentTerminal.App/Views/SettingsPages/GeneralSettings.xaml.cs, FluentTerminal.Models/ApplicationSettings.cs, FluentTerminal.Models/Requests/UpdateSettingsRequest.cs, FluentTerminal.SystemTray/Program.cs, FluentTerminal.SystemTray/Services/AppCommunicationService.cs, FluentTerminal.SystemTray/Services/TerminalsManager.cs
Introduces Settings options to
- enable/disable terminal output into log files (disabled by default)
- option to filter out escape sequences to be added into log files (enabled by default)
- path to directory where to create log files (default value is `ApplicationData.Current.LocalCacheFolder.Path` which usually equals to `C:\Users\%USERNAME%\AppData\Local\Packages\53621FSApps.FluentTerminal_87x1pks76srcp\LocalCache`)
Log files are created per terminal session and named to contain session creation timestamp and profile/executable name, for example, `20190708104435232_Powershell.log`.
Feature requested by https://github.com/jumptrading/FluentTerminal/issues/75
=> Settings option to dump terminal output into file.

FluentTerminal.App.ViewModels/MainViewModel.cs, FluentTerminal.App/Strings/de/Resources.resw, FluentTerminal.App/Strings/en/Resources.resw, FluentTerminal.App/Strings/es/Resources.resw, FluentTerminal.App/Strings/zh-CN/Resources.resw, FluentTerminal.App/Views/MainPage.xaml
In some places code and UI referring to SSH connections and profiles used the word "remote". Standardise on "SSH" (this is used more often anyway).
=> Standardise on naming of SSH related functionality

FluentTerminal.SystemTray/Utilities.cs
"Mute Terminal" functionality enhancement discussed in previous PR https://github.com/felixse/FluentTerminal/pull/437#issuecomment-509979156
- Tray process on startup searches for available conhost audio sessions. If no audio session is available, detached cmd.exe process is spawned to play bell sound. Tray process searches for conhost audio session again and sets relevant mute state.
- Since first spawned cmd.exe process seats in OS background, Fluent will play only single bell sound on very first launch of Tray process (and will not play sound on "Mute Terminal" option change or on each run of Tray process as it does currently).
=> Run background process to keep conhost audio session active.

FluentTerminal.App.Services/Constants.cs, FluentTerminal.App.Services/ITrayProcessCommunicationService.cs, FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs, FluentTerminal.App.Services/Implementation/TrayProcessCommunicationService.cs, FluentTerminal.App.Services/Terminal.cs, FluentTerminal.App.ViewModels/ITerminalView.cs, FluentTerminal.App.ViewModels/MainViewModel.cs, FluentTerminal.App.ViewModels/TerminalViewModel.cs, FluentTerminal.App/App.xaml.cs, FluentTerminal.App/FluentTerminal.App.csproj, FluentTerminal.App/Views/MainPage.xaml, FluentTerminal.App/Views/MainPage.xaml.cs, FluentTerminal.App/Views/TabBar.xaml, FluentTerminal.App/Views/TabBar.xaml.cs, FluentTerminal.App/Views/TerminalView.xaml.cs, FluentTerminal.App/Views/XtermTerminalView.xaml.cs, FluentTerminal.Client/src/index.ts, FluentTerminal.Client/src/xterm-addon-serialize/src/SerializeAddon.ts, FluentTerminal.Models/Requests/PauseTerminalOutputRequest.cs, FluentTerminal.Models/Responses/CreateTerminalResponse.cs, FluentTerminal.Models/Responses/PauseTerminalOutputResponse.cs, FluentTerminal.Models/Responses/TerminalResponse.cs, FluentTerminal.SystemTray/Services/AppCommunicationService.cs, FluentTerminal.SystemTray/Services/ConPty/ConPtySession.cs, FluentTerminal.SystemTray/Services/ITerminalSession.cs, FluentTerminal.SystemTray/Services/TerminalsManager.cs, FluentTerminal.SystemTray/Services/WinPty/WinPtySession.cs
Related to https://github.com/jumptrading/FluentTerminal/issues/109
- TabBar.xaml extended to support tabs drag and drop events to allow tabs dropping to another window or to tear off tab and create new window.
- Pause and resume TerminalSession's std output reading while xterm.js is not listening.
- Enable AlwaysShowTabs Settings option by default.
Known issue to be addressed in next step:
Not whole state of xterm.js is restored on drop of tab for restored buffer content (but new received terminal session is displaying fine).
=> Web browser like tabs

FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs, FluentTerminal.App.ViewModels/MainViewModel.cs, FluentTerminal.App.ViewModels/Settings/GeneralPageViewModel.cs, FluentTerminal.App/Strings/de/Resources.resw, FluentTerminal.App/Strings/en/Resources.resw, FluentTerminal.App/Strings/es/Resources.resw, FluentTerminal.App/Strings/zh-CN/Resources.resw, FluentTerminal.App/Views/SettingsPages/GeneralSettings.xaml, FluentTerminal.Models/ApplicationSettings.cs
Now that tags are draggable between windows this option will mainly cause confusion.
Follows on from #467.
=> Remove the "Always show tabs" option

FluentTerminal.App/Views/SettingsPage.xaml, FluentTerminal.App/Views/SettingsPage.xaml.cs
Fixes #465 I reported a few days ago.
Instead of dynamically adding a new item, adding it, setting and unsetting it again, I just add an hidden item that gets selected when about page is displayed.
=> FIXED: clicking on about in settings does not deselect previous item

FluentTerminal.App.Services/EventArgs/NewTabRequestedEventArgs.cs, FluentTerminal.App.ViewModels/MainViewModel.cs, FluentTerminal.App/App.xaml.cs, FluentTerminal.App/Strings/en/Resources.resw, FluentTerminal.App/Views/MainPage.xaml, FluentTerminal.App/Views/MainPage.xaml.cs, FluentTerminal.App/Views/TabBar.xaml.cs
Supersedes https://github.com/felixse/FluentTerminal/pull/475
Implements:
- Extended tab drop landing area visible only on dragging (appears NOT in drag source window)
- On tab drop to another window it calculates position for moved tab and inserts "restored" TerminalViewModel to calculated position.
=> Tab dropping extra space; Preserve drop position.

FluentTerminal.App.ViewModels/MainViewModel.cs, FluentTerminal.App.ViewModels/TerminalViewModel.cs, FluentTerminal.App/FluentTerminal.App.csproj, FluentTerminal.App/Strings/de/Resources.resw, FluentTerminal.App/Strings/en/Resources.resw, FluentTerminal.App/Strings/es/Resources.resw, FluentTerminal.App/Strings/zh-CN/Resources.resw, FluentTerminal.App/Utilities/InteractiveSurface.cs, FluentTerminal.App/Views/TabBar.xaml
Related to https://github.com/jumptrading/FluentTerminal/issues/160
`class InteractiveSurface : ContentControl` is introduced to wrap ListViewItem template content and provide `Hovered` property.
Also implements https://github.com/jumptrading/FluentTerminal/issues/161
"Close Tabs to the Left", "Close Tabs to the Right", "Close Other Tabs" menu options are added.
=> Show tab close button on hover.

FluentTerminal.Client/src/xterm-addon-serialize/src/SerializeAddon.ts
Related to https://github.com/jumptrading/FluentTerminal/issues/168
=> Serialize whole xterm.js buffer trimmed from the end.

FluentTerminal.SystemTray/Utilities.cs
Related to https://github.com/jumptrading/FluentTerminal/issues/180
@felixse it was discovered cruel CPU impact related to my recent changes for muting of audio sessions. This changelist removes "infinity" loops and adds back only 3 seconds wait timeout for such tasks as:
- Finding of spawned conhost.exe process by its parent process id
- Muting conhost's audio session (we able just loop the check for audio session availability)
=> Limit mute looping to 3 seconds timeout. More debug logs.

FluentTerminal.App/Views/MainPage.xaml, FluentTerminal.App/Views/MainPage.xaml.cs
Related to https://github.com/jumptrading/FluentTerminal/issues/165
Issue's description:
If the mouse goes over an active terminal window while a tab is being dragged, events are sent to that terminal causing it to scroll. This is unexpected and almost certainly not what you want.
Proposed solution background:
Scrolling, seems, happens because of [overflow-y: scroll](https://github.com/xtermjs/xterm.js/blob/master/css/xterm.css#L96). Pointer hovering with pressed mouse button in front of scroll bar edges causes not desired scrolling. `scroll` value can be changed to 'hidden' to remove scrolling, but in that case scroll bar control will not be rendered by WebView if scrollbar visibility is set to "always" in Fluent Settings.
Since solving of the issue directly in JavaScript looks too …
=> Do not send pointer events to WebView while dragging of tab happens.

FluentTerminal.SystemTray/FluentTerminal.SystemTray.csproj, FluentTerminal.SystemTray/ProcessUtils.cs, FluentTerminal.SystemTray/Services/ConPty/Processes/Process.cs, FluentTerminal.SystemTray/Services/ConPty/PseudoConsole.cs, FluentTerminal.SystemTray/Services/ConPty/PseudoConsolePipe.cs, FluentTerminal.SystemTray/Services/ConPty/Terminal.cs, FluentTerminal.SystemTray/Services/TerminalsManager.cs, FluentTerminal.SystemTray/Services/WinPty/WinPtySession.cs
- Clarified Dispose logic for ConPTY Terminal and Process
- Disposing a ConPTY Process now kills it and its children
- ConPTY Terminal now cleans up everything in its Dispose
- Wired up missing Dispose calls in various finalizers
- Removed ConPTY CTRL_CLOSE_EVENT handling. This event never seems to actually happen and the Terminal should get cleaned up eventually anyway.
Fixes https://github.com/jumptrading/FluentTerminal/issues/94
=> Ensure processes are killed for ConPTY sessions

FluentTerminal.App.Services/ITrayProcessCommunicationService.cs, FluentTerminal.App.Services/Implementation/TrayProcessCommunicationService.cs, FluentTerminal.App.Services/Terminal.cs, FluentTerminal.App.ViewModels/ITerminalView.cs, FluentTerminal.App.ViewModels/MainViewModel.cs, FluentTerminal.App.ViewModels/OverlayViewModel.cs, FluentTerminal.App.ViewModels/TerminalViewModel.cs, FluentTerminal.App/Adapters/DispatcherTimerAdapter.cs, FluentTerminal.App/Converters/TerminalViewModelToViewConverter.cs, FluentTerminal.App/Utilities/DebouncedAction.cs, FluentTerminal.App/Views/TerminalView.xaml.cs, FluentTerminal.App/Views/XtermTerminalView.xaml.cs
There are a bunch of things prevented GC from objects trashing:
- Keeping object references in collections without after usage removal ( `TrayProcessCommunicationService._terminalOutputHandlers` and `TerminalViewModelToViewConverter._viewDictionary` ).
- Not unsubscribed events.
- Strong references to methods used in `DebouncedAction`.
- Missed disposing of `WebSocketServer` instance and connection closing.
- Infinite background task running from `XTermTerminalView.StartMediatorTask`
- Manually added UI elements to a visual tree are not removed automatically
- Exposing ViewModel references to XAML creates strong refs
=> Resolve GC's disposal issues.

FluentTerminal.App/Views/XtermTerminalView.xaml.cs
It somehow caused keyboard events blocking for XtermTerminalView.
=> Avoid static FleckLog.LogAction reset.

FluentTerminal.SystemTray/ProcessUtils.cs
@felixse exception seems crashes SystemTray pretty often
=> Ignore Win32Exception on attempt to kill pty process tree.

FluentTerminal.Client/src/index.ts
Related to discussion https://github.com/jumptrading/FluentTerminal/issues/106
Also adds `tmux` vertical pane border character.
=> Extend list of word separators for text selection.

FluentTerminal.App.ViewModels/MainViewModel.cs, FluentTerminal.App.ViewModels/TerminalViewModel.cs, FluentTerminal.App/Utilities/DebouncedAction.cs, FluentTerminal.App/Views/TerminalView.xaml.cs, FluentTerminal.App/Views/XtermTerminalView.xaml.cs
- Reset Action reference from DebouncedAction instance.
- Prevent crash on close of uninitilized terminal.
Related to https://github.com/jumptrading/FluentTerminal/issues/204, https://github.com/jumptrading/FluentTerminal/issues/194
https://github.com/jumptrading/FluentTerminal/issues/204 was introduced by recent changes to avoid memory leaks.
=> Crash on close; Resizing leads to freezed terminals.

FluentTerminal.App.ViewModels/MainViewModel.cs
Avoid unhandled `ArgumentOutOfRange` exception on async insert.
Related to https://github.com/jumptrading/FluentTerminal/issues/194
=> Validate new terminal position index on insert.

FluentTerminal.SystemTray/Services/ConPty/ConPtySession.cs, FluentTerminal.SystemTray/Services/ConPty/Terminal.cs
Related to https://github.com/jumptrading/FluentTerminal/issues/194
Sending user input to not yet fully initialized terminal leads to crash on unhandled null pointer reference exception.
=> Avoid crash on user input processing before ConPTY is fully initialized.

FluentTerminal.App/App.xaml.cs
Fixes #81
Also fixes #512 as a side effect
- `ApplicationViewSwitcher.DisableSystemViewActivationPolicy()` is needed to prevent the new window opened next to the existing window in another desktop
- Local function `ShowAsStandaloneAsync()` is needed so that the newly created window (or tab depending on the setting) is activated correctly
=> Support Shift+Click and "Open in new desktop" feature

FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs, FluentTerminal.App.ViewModels/Settings/TerminalPageViewModel.cs, FluentTerminal.App.ViewModels/Utilities/WebViewSpecialCharEncoder.cs, FluentTerminal.App/Strings/en/Resources.resw, FluentTerminal.App/Views/SettingsPages/TerminalSettings.xaml, FluentTerminal.App/Views/XtermTerminalView.xaml.cs, FluentTerminal.Client/src/index.ts, FluentTerminal.Models/TerminalOptions.cs
Introduces "Select-by-word characters" Terminal Settings option.
Related to https://github.com/jumptrading/FluentTerminal/issues/106
It's turned out that WebView doesn't work well with passing following symbols ",',\ as part of the script to be executed by JS engine. As workaround the encoding/decoding of special symbols happens both on C# and JS sides for Terminal Options values.
=> Terminal settings option to customize XTermJS word separator chars list.

FluentTerminal.App.Services/IKeyboardCommandService.cs, FluentTerminal.App.Services/Implementation/KeyboardCommandService.cs, FluentTerminal.App.Services/Terminal.cs, FluentTerminal.App.ViewModels/MainViewModel.cs, FluentTerminal.App/Adapters/ApplicationViewAdapter.cs, FluentTerminal.App/App.xaml.cs, FluentTerminal.App/Converters/TerminalViewModelToViewConverter.cs, FluentTerminal.App/Views/MainPage.xaml.cs, FluentTerminal.App/Views/TabBar.xaml.cs, FluentTerminal.App/Views/TerminalView.xaml.cs, FluentTerminal.App/Views/XtermTerminalView.xaml.cs, FluentTerminal.RuntimeComponent/WebAllowedObjects/TerminalBridge.cs
- Force GC.Collect() on closing of terminal;
- Prepare MainPage, MainViewModel, TabBar, TerminalBridge for disposal.
related to https://github.com/jumptrading/FluentTerminal/issues/190
With PR's changes applied the memory consumption after 50 new windows opened and closed should be decreased from ~1100 MB to ~260 MB.
=> Avoid memory leaks after terminal window is closed.

Install.ps1
Sometimes when an update has an issue it can be useful to downgrade, this is what this change allows for (especially when using Chocolatey for package management).
The [official Powershell documentation](https://docs.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=win10-ps) was not very verbose about this flag - https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1398
So I'm assuming the flag has a similar behaviour as the one described here: https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-force-update-from-any-version
=> Enable app downgrading in the install script

FluentTerminal.SystemTray/Services/TerminalsManager.cs
Related to https://github.com/jumptrading/FluentTerminal/issues/224
It seems that running CLI process might error out, but user input writing to PTY still happens and crashes tray process with unhandled IOException.
It should be fine to ignore user input in case if IO was closed/invalidated.
So far, the issues always started from receiving "lost connection to agent" error from WinPty https://github.com/microsoft/node-pty/blob/master/deps/winpty/src/libwinpty/winpty.cc#L277
=> Handle IOException on user input write to pty.

FluentTerminal.App.Services/Implementation/DefaultValueProvider.cs, FluentTerminal.App.ViewModels/Profiles/SshConnectViewModel.cs, FluentTerminal.App.ViewModels/Settings/GeneralPageViewModel.cs, FluentTerminal.App.ViewModels/Settings/ProfilesPageViewModel.cs, FluentTerminal.App.ViewModels/Settings/SshProfilesPageViewModel.cs, FluentTerminal.App/ViewModels/CommandProfileProviderViewModel.cs, FluentTerminal.App/Views/SettingsPages/GeneralSettings.xaml, FluentTerminal.Models/ApplicationSettings.cs, FluentTerminal.Models/SshProfile.cs
Moves back global option to have preferred pty mode globally (ConPty or WinPty).
Related to https://github.com/jumptrading/FluentTerminal/issues/223
It allows to save few seconds of time on each opening of remote machine from SSH dialogs.
=> Default to WinPty settings option.

FluentTerminal.App/App.xaml.cs
#513 was not perfect. Currently there's an activation problem when opening a new window in a new desktop.
1. Launch Fluent Terminal.
2. Switch to another desktop which has no Fluent Terminal window.
3. Open new window by clicking the task bar icon.
4. The new window is displayed in the foreground but is not active, that is, you can't type into the window until you click it.
With this PR it works as expected **in most cases**. I admit it sometimes fails to activate correctly, but I haven't found the cause so far.
=> Fix activation problem when opening a new window in a new desktop

FluentTerminal.App/App.xaml.cs, FluentTerminal.SystemTray/Program.cs
Ensuring that any unhandled TPL exceptions are logged. Without this, exceptions in fire-and-forget tasks (not awaited tasks) won't be logged.
=> Logging UnobservedTaskException

FluentTerminal.App/Dialogs/CustomCommandDialog.xaml, FluentTerminal.App/Dialogs/CustomCommandDialog.xaml.cs
**Please merge https://github.com/felixse/FluentTerminal/pull/581 first! This one builds upon it.**
Solves https://github.com/jumptrading/FluentTerminal/issues/200.
Selecting a suggested text from auto-complete list in "Quick Launch" now works as follows:
- Selecting with `Enter` key immediately closes the dialog and launches the command;
- Selecting with `Tab` key selects the command and moves focus to the next control ("Advanced Options");
- Selecting with mouse click / tap selects the command, and the command text box retains focus.
=> `Enter` selection in "Quick Launch" immediately launches the command

FluentTerminal.App/Dialogs/CustomCommandDialog.xaml.cs
Fixes a bug noticed by @mjs with `Tab` selection not working if a user enters some filtering text.
=> Fixed a bug with Tab selection in Quick Launch dialog

FluentTerminal.App.Services/IApplicationView.cs, FluentTerminal.App.ViewModels/FluentTerminal.App.ViewModels.csproj, FluentTerminal.App.ViewModels/MainViewModel.cs, FluentTerminal.App.ViewModels/Profiles/ProfileProviderViewModelBase.cs, FluentTerminal.App.ViewModels/Profiles/SshConnectViewModel.cs, FluentTerminal.App.ViewModels/Settings/AboutPageViewModel.cs, FluentTerminal.App.ViewModels/TerminalViewModel.cs, FluentTerminal.App/Adapters/ApplicationViewAdapter.cs, FluentTerminal.App/App.xaml.cs, FluentTerminal.App/FluentTerminal.App.csproj, FluentTerminal.App/Utilities/DispatcherExtensions.cs, FluentTerminal.App/ViewModels/CommandProfileProviderViewModel.cs, FluentTerminal.App/Views/XtermTerminalView.xaml.cs
**Merge https://github.com/felixse/FluentTerminal/pull/598 first**
Part of https://github.com/jumptrading/FluentTerminal/issues/238
The key reason for the change is removing `ManualResetEventSlim` and `SemaphoreSlim` which were used so far during the initialization of `XtermTerminalView`, and replacing them with much lighter `TaskCompletionSource` mechanism.
=> XtermTerminalView initialization simplified

FluentTerminal.App.ViewModels/MainViewModel.cs, FluentTerminal.App.ViewModels/Menu/SeparatorMenuItemViewModel.cs, FluentTerminal.App/Converters/MenuItemViewModelBaseToMenuFlayoutItemBaseConverter.cs
Nice work with menu separator! Few fixes though:
- `SeparatorMenuItemViewModel` should override `EquivalentTo` method, not introduce `Equals`. Fixed.
- ReSharper doesn't support pattern matching in `switch` (thus causing me some troubles), so I've changed it to old-fashion `if` - `is` implementation.
- Minor reordering in `MainViewModel`.
=> Minor changes in app menu implementation.

FluentTerminal.App.ViewModels/TerminalViewModel.cs
Fixes the following bug: https://github.com/jumptrading/FluentTerminal/issues/246
This is another bug introduced by my latest PRs. To explain the reason: Earlier `XtermTerminalView.Terminal_KeyboardCommandReceived` method was always executed in the UI thread (it was called from one of the jobs from `_dispatcherJobs` collection). When removed the collection I didn't want to put all these jobs in UI thread (in order to offload it), but only those which actually require UI thread. So now the mentioned method is executed in some other thread, and I haven't changed that even in this fix. I've isolated only two parts from the whole method which are actually requiring the UI thread. The rest of the method works well without UI thread anyway.
Sorry for this one!
=> Fixed a bug with keyboard shortcuts crushing the app

FluentTerminal.App/Views/XtermTerminalView.xaml.cs
It's a trivial PR. As you can see in the code, I've only reduced delays in `XterTerminalView` in order to accomplish better responsiveness. I'm quite sure that the new delays are safe since they are kinda accumulating (action happens only after this period of silence). I've played with these values, and it looks great to me, yet safe. It's your call...
=> Resize and options changed delays reduced in XtermTerminalView

FluentTerminal.App/Dialogs/SshInfoDialog.xaml
Fixes https://github.com/jumptrading/FluentTerminal/issues/248
@felixse, it looks that you've introduced this bug when moving from `Binding` and `DataContext` to `x:Bind` and `ViewModel` property. No matter this particular bug, I don't like it. Binding to `ViewModel` which is property of some object (in this case `SshInfoDialog`) which doesn't implement `INotifyPropertyChange` assumes some underlying overhead (how UI _knows_ that `ViewModel` property is changed if we haven't implemented `INotifyPropertyChanged`). Such bindings are source of [well known memory leaks in WPF](https://blog.jetbrains.com/dotnet/2014/09/04/fighting-common-wpf-memory-leaks-with-dotmemory/). Maybe things are better with UWP apps, but I would rather rely on my `INotifyPropertyChanged` implementation than put …
=> Hidding "Mosh Prots" in "SSH Info" dialog if "Use Mosh" isn't selected

FluentTerminal.App.ViewModels/ProfileViewModelBase.cs, FluentTerminal.App/Views/SettingsPages/SshProfileSettings.xaml
Fixes https://github.com/jumptrading/FluentTerminal/issues/249
The cause for the error was some obsolete code which is now removed.
=> Fixed binding errors in Settings -> SSH Profiles

FluentTerminal.App.Services.Test/SettingsServiceTests.cs, FluentTerminal.App.Services/ISettingsService.cs, FluentTerminal.App.Services/Implementation/MoshBackwardCompatibility.cs, FluentTerminal.App.Services/Implementation/SettingsService.cs, FluentTerminal.App/App.xaml.cs, FluentTerminal.App/Dialogs/ShellProfileSelectionDialog.xaml.cs, FluentTerminal.App/Services/CommandHistoryService.cs, FluentTerminal.App/Utilities/JumpListHelper.cs, FluentTerminal.SystemTray/Program.cs
Related to https://github.com/jumptrading/FluentTerminal/issues/237
Suspicious `Task.Run...` call is removed, but it's already explained in details in https://github.com/jumptrading/FluentTerminal/issues/237#issuecomment-557353593. Here I need to explain why I've changed `GetShellProfiles` and `GetSshProfiles` methods in `SettingsService`:
Previously the methods were returning `List<ShellProfile>` and `List<SshProfile>`, although the method signature states that they return `IEnumerable<ShellProfile>` and `IEnumerable<SshProfile>`, respectively. The problem is that you don't have to return `List<T>` when you advertise it as `IEnumerable<T>`, especially no in cases when creating the list is expensive. The difference is that when returning `List<T>` you're always creating **the whole list, …
=> Getting profiles from ISettingsService and optimizing JumpList

FluentTerminal.App.Services/Implementation/FluentTerminalThemeParser.cs, FluentTerminal.App.Services/Implementation/ITermThemeParser.cs
Related to https://github.com/jumptrading/FluentTerminal/issues/237
I've isolated this in a separate PR just to explain some of the things I am changing, and the reason for the change. Changes I've made here are removing `async` keyword if it isn't actually needed. `async`/`await` construct makes compiler break down the method internally into few methods, thus introducing some overhead at compile and run time. The overhead isn't too big, but there's no reason to have it anyway, if `async` isn't needed in the first place.
Example 1, old code:
```
public async Task<ExportedTerminalTheme> Import(string fileName, Stream fileContent)
{
return await DeserializeTheme<ExportedTerminalTheme>(fileName, fileContent);
}
```
New code:
```
public Task<ExportedTerminalTheme> Import(string fileName, …
```
=> Fixing async patterns in IThemeParser.

FluentTerminal.RuntimeComponent/WebAllowedObjects/TerminalBridge.cs
Fixes https://github.com/jumptrading/FluentTerminal/issues/255
Dunno what to say... Take a look at the description in the linked issue... It looks that your previous inversion _if-in-UI-thread-launch-in-another-thread_ was good for this particular case... But it looks that UI thread isn't needed there at all, so I've removed it.
=> Fixed app-crashes-on-tab-detach bug

FluentTerminal.App.Services/Utilities/I18N.cs
Solves https://github.com/jumptrading/FluentTerminal/issues/259
For simple string translation we didn't need `ResourceLoader.GetForCurrentView()` anyway.
=> App crash on validation bug fixed

FluentTerminal.App.Services/Adapters/ApplicationDataContainerAdapter.cs, FluentTerminal.App.Services/Implementation/SettingsService.cs, FluentTerminal.App.Services/Implementation/TrayProcessCommunicationService.cs, FluentTerminal.App.Services/Utilities/PreserveDictionaryKeyCaseContractResolver.cs, FluentTerminal.App.Services/Utilities/TerminalThemeContractResolver.cs
Solves https://github.com/jumptrading/FluentTerminal/issues/261
Surprisingly for me, it turned out that `JsonConvert.SerializeObject`, with default settings **changes dictionary keys to lowercase!** I cannot believe that NewtonSoft JSON did such dumb mistake!
=> Bug with env var names becoming lowercase fixed

FluentTerminal.Client/src/index.ts
Fixes https://github.com/jumptrading/FluentTerminal/issues/265
=> Disable WebView zooming to prevent crash on too small font size.

FluentTerminal.App.ViewModels/Profiles/SshConnectViewModel.cs
Fixes #685 
The change was introduced in https://github.com/felixse/FluentTerminal/commit/6868bfa7cac4196923985ac47e5cbc34b50e1f80#diff-0c0ed937950c1407065c4863a41838ddR200
Have tested locally both mosh and ssh.
Note: SSH profile should be re-saved to generate new cli arguments and update old incorrect args in user settings.
=> Rollback to use double quotes around identity file for ssh cli cmd.

README.md
Scoop enables app sideloading from the manifest itself. Also, the manifest has now been updated for 0.7.0.0.
=> Update README.md for Scoop

FluentTerminal.App/Actions/FocusAction.cs
Focus was set before the control was visible most of the time. This fix will wait for the control to load if it is not visible. If it managed to load fast enough it will grab focus immediately instead.
=> Fix for lack of focus on search textbox.

FluentTerminal.App.ViewModels/MainViewModel.cs, FluentTerminal.App.ViewModels/TerminalViewModel.cs, FluentTerminal.App/Views/TerminalView.xaml, FluentTerminal.App/Views/TerminalView.xaml.cs
The crash occured because the popup is treated like the mainwindow and the main window grabs keypresses. Because of this a paste command can be executed on the main window when attempting to paste into the search box (when ctrl-c is used as a paste binding).
Adding an empty binding for copy and paste resolves this. Additionally it was required to prevent the terminal view from handling paste requests to prevent pasting to searchbox and terminal at the same time.
=> Fix for a crash in search popup.

FluentTerminal.App/Views/TerminalView.xaml.cs
When the search flyout is visible but not focused the text is now selected when search focus is requested.
This behavior mimics other tools.
=> Adjusted the behavior of search so that the previous text is selected when search is active

Explorer Context Menu Integration/Install_with_icon.bat
The icon does not copy when you have a path with blanks. Added quotes to copy in any case
=> added quotes in the icon copy line (first line)
